# Generated by Django 5.1.4 on 2025-01-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_favadvertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favadvertisement',
            name='is_user_creator',
        ),
    ]
