# Generated by Django 5.1.4 on 2024-12-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scope_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        ),
    ]
