# Generated by Django 5.1.4 on 2024-12-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_tag_articles_article_tegs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tegs',
            new_name='tags',
        ),
    ]
