# Generated by Django 5.1.4 on 2024-12-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_scope_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
