# Generated by Django 5.1.4 on 2024-12-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
