# Generated by Django 5.1.3 on 2024-12-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
